logiq-flash:
  replicaCount: 3
  service:
    type: NodePort
  image:
    tag: 2.0.6
    pullPolicy: IfNotPresent
  environment:
    flags_extra: "-s3_partition_object_max_size 8388608"
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    serviceMonitor:
      enabled: true
      selector:
        release: prometheus
  resources:
    requests:
      cpu: "1000m"
    limits:
      cpu: "4000m"

flash-discovery:
  fullnameOverride: flash-discovery
  image:
    tag: 2.0.1
    pullPolicy: IfNotPresent
  replicaCountDiscovery: 2
  persistence:
    enabled: true
    size: 2Gi

redis:
  enabled: true
  fullnameOverride: redis
  usePassword: false
  cluster:
    slaveCount: 2
  master:
    disableCommands: []
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
                - redis
          topologyKey: "kubernetes.io/hostname"
  slave:
    disableCommands: []
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
                - redis
          topologyKey: "kubernetes.io/hostname"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    selector:
      release: prometheus
  podSecurityPolicy:
    create: true
    rbac:
      create: true
      role:
        rules:
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - use
          resourceNames:
          - redis
  securityContext:
    enable: true
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount:
    create: true
    name: redis

postgres:
  enabled: true
  fullnameOverride: postgres
  postgresqlPostgresPassword: postgres
  postgresqlUsername: postgres
  postgresqlDatabase: postgres
  postgresqlPassword: postgres
  postgresqlExtendedConf:
    maxConnections: "800"
    sharedBuffers: "2048MB"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    additionalLabels:
      release: prometheus
  persistence:
    size: 20Gi
  resources:
    requests:
      memory: "8Gi"
      cpu: "2000m"
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount:
    enabled: true
    name: postgres

flash-coffee:
  service:
    type: ClusterIP
  coffee:
    replicaCount: 1
    image:
      tag: brew.2.0.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        cpu: "1000m"
  coffee_worker:
    replicaCount: 4
    image:
      tag: brew.2.0.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        cpu: "1000m"

s3-gateway:
  mode: distributed
  s3gateway:
    enabled: false
  defaultBucket:
    enabled: true
  fullnameOverride: s3-gateway
  accessKey: logiq_access
  secretKey: logiq_secret
  metrics:
    serviceMonitor:
      enabled: false
  buckets:
    - name: logiq
      policy: none
      purge: false
  persistence:
    enabled: true
    size: 10Gi
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  serviceAccount:
    create: true
    name: s3-gateway

ingress:
  enabled: true
  name: logiq-ingress
  tlsEnabled: false
  tlsSecretName: null

kubernetes-ingress:
  defaultBackend:
    replicaCount: 2
  controller:
    replicaCount: 2
    ingressClass: logiq-ingress
    service:
      type: LoadBalancer
    defaultTLSSecret:
      enabled: false
      secret: null
  podSecurityPolicy:
    enabled: true
  serviceAccount:
    create: true
    name: ingress-nginx

prometheus-operator:
  fullnameOverride: prometheus
  persistence:
    enabled: true
    size: 20Gi

logiqctl:
  image:
    repository: logiqai/logiqctl
    tag: 2.0.1
    pullPolicy: IfNotPresent

global:
  domain: null
  cloudProvider: aws
  enableMetricsServer: false
  sharedSecretName: logiq-shared-secret
  job:
    ttlSecondsAfterFinished: 60
  toolbox:
    image:
      repository: logiqai/toolbox
      tag: 2.0.1
  environment:
    logiq_flash_host: logiq-flash
    logiq_flash_port: 9999
    redis_opts: true
    redis_host: "redis-master"
    redis_port: "6379"
    postgres_host: "postgres"
    postgres_port: "5432"
    postgres_user: "postgres"
    postgres_password: "postgres"
    postgres_db: "postgres"
    postgres_coffee_db: "coffee"
    s3_url: "http://s3-gateway:9000"
    s3_access: "logiq_access"
    s3_secret: "logiq_secret"
    s3_bucket: "logiq"
    s3_region: "us-east-1"
    mail_server: "smtp-mail-server"
    mail_port: "587"
    mail_username: "user"
    mail_password: "password"
    mail_default_sender: "flash-admin@foo.com"
    admin_name: "flash-admin@foo.com"
    admin_password: "flash-password"
    admin_org: "flash-org"
    admin_email: "flash-admin@foo.com"
    license: "license/license_medium.jws"
    upload_dashboard: true
    cluster_id: LOGIQ
    awsServiceEndpoint: https://s3.us-east-1.amazonaws.com
  persistence:
    storageClass: "standard"
  chart:
    prometheus: true
    postgres: true
    redis: true
    s3-gateway: true
